version: 2.0
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 4473901b40a4467ff2db5da9271671ef7545c987b38f5f1490ec254ebc3778e0
    docker:
      - image: "mileschou/xdebug:8.1-alpine"
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: |
            composer self-update
            composer install -n --prefer-dist
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            docker-php-ext-enable xdebug zip xmlreader
            ./cc-test-reporter before-build
            sudo vendor/bin/phpunit --coverage-clover clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
